### ISSUE TITLE
ModuleNotFoundError: No module named 'botasaurus.decorators'

### ISSUE THREAD

**Issue by chocolaid** [omkarcloud/tripadvisor-scraper#38]
I installed the packages and still getting an error when i run `py main.py`

Traceback (most recent call last):
  File "C:\Users\BLOOD\Desktop\tripadvisor-scraper\main.py", line 1, in <module>
    from src import Tripadvisor
  File "C:\Users\BLOOD\Desktop\tripadvisor-scraper\src\__init__.py", line 1, in <module>
    from .tripadvisor import Tripadvisor
  File "C:\Users\BLOOD\Desktop\tripadvisor-scraper\src\tripadvisor\__init__.py", line 1, in <module>
    from .tripadvisor_scraper import Tripadvisor
  File "C:\Users\BLOOD\Desktop\tripadvisor-scraper\src\tripadvisor\tripadvisor_scraper.py", line 4, in <module>
    from .write_output import write_output
  File "C:\Users\BLOOD\Desktop\tripadvisor-scraper\src\tripadvisor\write_output.py", line 2, in <module>
    from botasaurus.decorators import print_filenames
ModuleNotFoundError: No module named 'botasaurus.decorators'

**Comment by Chetan11-dev** [comment]
Resolved in latest update
