### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by khachmush** [omkarcloud/tripadvisor-scraper#39]
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/botasaurus_server/task_executor.py", line 150, in run_task
    result = fn(
             ^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/botasaurus/task_decorator.py", line 172, in wrapper_requests
    current_result = run_task(data_item, False, 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/botasaurus/task_decorator.py", line 140, in run_task
    raise error
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/botasaurus/task_decorator.py", line 85, in run_task
    result = func( data)
             ^^^^^^^^^^^
  File "/workspace/tripadvisor-scraper/src/get_tripadvisor_listings.py", line 8, in get_tripadvisor_listings
    return Tripadvisor.get_hotels(data["search_queries"], data["max_results"], data["api_key"], data["enable_detailed_extraction"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tripadvisor-scraper/src/tripadvisor/tripadvisor_scraper.py", line 83, in get_hotels
    return remove_duplicates_by_key(perform_query(search_query, max_results, api_key, enable_detailed_extraction, "hotels"), "id")
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/tripadvisor-scraper/src/tripadvisor/tripadvisor_scraper.py", line 47, in perform_query
    if item.get('error'):
       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Chetan11-dev** [comment]
Resolved!
